
top_builddir = ../../build/
web_site_dir = $(top_builddir)web-site/
web_site_css_bundle_dir = $(web_site_dir)css/
top_srcdir = ../../


NPX = npx
MKDIR = mkdir
MKDIR_P = mkdir -p

all: index-css-r

index-css-r:
	@$(MAKE) -C scss index-css-r

.PHONY: all
.PHONY: index-css-r

# vi: se ts=4 sw=4 noet:
