
all: index-js-r php-deploy-in-web-site-r

index-js-r:
	@$(MAKE) -C js index-js

index-css-r:
	@$(MAKE) -C style index-css-r

php-lint-r:
	@$(MAKE) -C php php-lint-r

php-deploy-in-web-site-r:
	@$(MAKE) -C php php-deploy-in-web-site-r

.PHONY: all
.PHONY: index-js-r
.PHONY: index-css-r
.PHONY: php-lint-r
.PHONY: php-deploy-in-web-site-r

# vi: se ts=4 sw=4:
